### ISSUE TITLE
Misconfigured Node.js workflow

### ISSUE THREAD

**Issue by aravindvnair99** [abhinavsri360/GDSC-Lead-Map#18]
Node.js workflow is building twice which isn't necessary: https://github.com/abhinavsri360/GDSC-Lead-Map/runs/2321242275?check_suite_focus=true

It is also set to deploy on pull requests which means if an incorrect PR is sent, it will deploy the incorrect version:

https://github.com/abhinavsri360/GDSC-Lead-Map/blob/ff80168b8d42cf434dba9c03ab4aa3ac740d8eaf/.github/workflows/node.js.yml#L6-L10

Node.js 15 is used:
https://github.com/abhinavsri360/GDSC-Lead-Map/blob/ff80168b8d42cf434dba9c03ab4aa3ac740d8eaf/.github/workflows/node.js.yml#L19

But `Chokidar 2 will break on node v14+`: https://github.com/abhinavsri360/GDSC-Lead-Map/runs/2321242275?check_suite_focus=true#step:4:5

Better to use 12 instead.

**Comment by abhinavsri360** [comment]
@aravindvnair99 
I just thought about 

```
pull_request:
  branches: [main]
```

Don't you think this will run the flow whenever a new PR is made(for the changes made by the new PR, just like netlify does)?

**Comment by aravindvnair99** [comment]
> @aravindvnair99
> I just thought about
> 
> ```
> pull_request:
>   branches: [main]
> ```
> 
> Don't you think this will run the flow whenever a new PR is made(for the changes made by the new PR, just like netlify does)?

@abhinavsri360 It will for any PRs to `main` branch. But you are deploying to a production server, unlike Netlify which is deploying to a development server.

**Comment by abhinavsri360** [comment]
Ohh got it!
Thanks 🚀
