### ISSUE TITLE
gdscleads.team not responding

### ISSUE THREAD

**Issue by abhinavsri360** [abhinavsri360/GDSC-Lead-Map#63]
https://www.gdscleads.team/ won't be available for 24 hours approximately, shifting the hosting platform from Netlify to GitHub due to the limit on the monthly quota provided by Netlify.
Please be patient if you find that the link is not working/responding. DNS changes take approximately any time from 10 minutes to 10 hours, so please be patient.
Furthermore, you can find the web app hosted here: https://abhinavsri360.github.io/GDSC-Lead-Map

Thanks.

**Comment by aravindvnair99** [comment]
@abhinavsri360 https://abhinavsri360.github.io/GDSC-Lead-Map currently redirects to http://gdscleads.team

```console
$ curl -I https://abhinavsri360.github.io/GDSC-Lead-Map
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 162
Server: GitHub.com
Content-Type: text/html
Location: http://gdscleads.team
```

**Comment by abhinavsri360** [comment]
Bruhh DNS setup is taking time, wait lemme remove the domain.
Thanks for pointing it out, and I just wish GitHub had an option to send stickers.

**Comment by abhinavsri360** [comment]
removed the domain, for now, will try back in a few hours.

**Comment by abhinavsri360** [comment]
Update: can be viewed here: https://gdscleadmap.netlify.app/

**Comment by aravindvnair99** [comment]
@abhinavsri360 You can check how long the change will take by checking the TTL of the A record:

[gdscleads.team](https://mxtoolbox.com/SuperTool.aspx?action=a%3agdscleads.team&run=toolpage)
[gdscleadmap.netlify.app](https://mxtoolbox.com/SuperTool.aspx?action=a%3agdscleadmap.netlify.app&run=toolpage)
[abhinavsri360.github.io](https://mxtoolbox.com/SuperTool.aspx?action=a%3aabhinavsri360.github.io&run=toolpage)

Also, for now, you can set the TTL as low as possible to make the change faster and later set a higher number.

Currently, there isn't any nameserver configured for [gdscleads.team](https://mxtoolbox.com/SuperTool.aspx?action=dns%3agdscleads.team&run=toolpage)

**Comment by abhinavsri360** [comment]
Yes there are none, I removed the domain completely from netlify. Now waiting for netlify to reconfigure the DNS servers

**Comment by aravindvnair99** [comment]
> Yes there are none, I removed the domain completely from netlify. Now waiting for netlify to reconfigure the DNS servers

@abhinavsri360 Ah alright, the easiest way to switch and that too without downtime is/was to:

- Point domain to GitHub instead of Netlify. (Will take/would have taken 20 seconds for global propagation)
- Switch nameserver back to the original provider. (Will take/would have taken 60 minutes for global propagation)

**Comment by abhinavsri360** [comment]
Previously domains were being controlled by netlify itself, so changed the nameservers to default just now. It might take some time and it'll be back to what I did and read until now.

**Comment by abhinavsri360** [comment]
I just read in the docs of GitHub pages about DNS changes. It says, "DNS changes can take up to 24 hours to propagate."
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by aravindvnair99** [comment]
@abhinavsri360 So far headed in the right direction: https://mxtoolbox.com/SuperTool.aspx?action=dns%3agdscleads.team&run=toolpage

**Comment by abhinavsri360** [comment]
![Screenshot from 2021-04-14 14-23-39](https://user-images.githubusercontent.com/44001310/114682801-0e10c000-9d2d-11eb-95cd-26507a77da6e.png)
Indeed, so far so good. Just waiting for this :))

**Comment by abhinavsri360** [comment]
https://gdscleads.team/ is working now, I repeat, the domain is working now! 🎉
