### ISSUE TITLE
Changing default map position and zoom level

### ISSUE THREAD

**Issue by aravindvnair99** [abhinavsri360/GDSC-Lead-Map#89]
I was thinking we should change the default view of the map from this:

![image](https://user-images.githubusercontent.com/22199259/115154908-ead27180-a09a-11eb-8f09-782c01a10414.png)

To this:

![image](https://user-images.githubusercontent.com/22199259/115154884-c37ba480-a09a-11eb-9488-fe02409a19b9.png)

In this way, we can make it more inclusive, and people wouldn't think it's only for the Indian subcontinent.

**Comment by abhinavsri360** [comment]
For sure, this can be done.
