### ISSUE TITLE
Add CLI to Compress and optimise images

### ISSUE THREAD

**Issue by aravindvnair99** [abhinavsri360/GDSC-Lead-Map#92]
Images are not compressed, thus leading to longer load times.

![image](https://user-images.githubusercontent.com/22199259/115228126-01c2a380-a12f-11eb-87f9-7b9e9d03243b.png)

**Comment by abhinavsri360** [comment]
Should we use python 👀

**Comment by aravindvnair99** [comment]
> Should we use python 👀

@abhinavsri360 I'm sorry, I didn't get you. Python for?

**Comment by abhinavsri360** [comment]
> > Should we use python eyes
> 
> @abhinavsri360 I'm sorry, I didn't get you. Python for?

Use a python script to run on build and compress images?

**Comment by aravindvnair99** [comment]
> Use a python script to run on build and compress images? Though we can do this every time but how about automation?

@abhinavsri360 Yep, it would be good to automate. And also convert to `jpg`, if it's `png` or any other format. Instead of Python, I would recommend [ImageMagick](https://imagemagick.org/index.php) directly on CLI as that's faster. Python will be an unnecessary overhead.

We can do lossless compression and file format conversion with it. Also, switching to WebP would be an even bigger advantage.

**Comment by abhinavsri360** [comment]
Yeah, I mean this would be the best, I'll have to go through the documentation to add this tool. Do you have any idea about that?

**Comment by aravindvnair99** [comment]
> Yeah, I mean this would be the best, I'll have to go through the documentation to add this tool. Do you have any idea about that?

@abhinavsri360 Yep, I've used it before. When I switched to WebP, I noticed big improvements. Here's something I found: https://developers.google.com/speed/webp/docs/cwebp

Also, https://caniuse.com/webp

**Comment by abhinavsri360** [comment]
Nice, I'll go through them, this is noice.

**Comment by aravindvnair99** [comment]
@abhinavsri360 Viable solutions:

1. https://developers.google.com/speed/webp/docs/cwebp (Compress an image file to a WebP file)
2. https://imagemagick.org/script/command-line-processing.php (Tool with multiple capabilities such as compress, scale, resize, etc)
3. https://github.com/marketplace/imgbot (Easiest - automatically sends PRs)

**Comment by abhinavsri360** [comment]
Adding Imgbot is super eazy, I added it tho.

**Comment by abhinavsri360** [comment]
Thanks, @aravindvnair99
